<a href="https://colab.research.google.com/github/josxac/MATA-D/blob/main/CMPU_250_MATA_D_Qualitative_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#libraries

# run this first
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

# suppress warnings
pd.options.mode.chained_assignment = None
pd.options.mode.copy_on_write = True

In [36]:
#read the file
qual = pd.read_csv('MATA-D_Qualitative.csv')

#make a copy of it that does not change when housing is changed
copy = qual.copy(deep = True)

#define columns as the names in row 3
qual.columns = qual.iloc[2]

#remove all extra rows with no data
qual = qual.head(241)

#drop row 3, since they are the column names
qualc = qual.drop(qual.index[2])

qualc

2,INCIDENT ID,INDUSTRY,LOCATION,YEAR,Wrong Time,Wrong Type,Wrong Object,Wrong Place,Observation Missed,False Observation,...,Temperature,Sound,Humidity,Illumination,Other,Adverse ambient conditions,Excessive demand,Inadequate work place layout,Inadequate team support,Irregular working hours
0,NaN,NaN,NaN,NaN,Action,NaN,NaN,NaN,Specific Cognitive Functions,NaN,...,Ambient Conditions,NaN,NaN,NaN,NaN,NaN,Working Conditions,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,Execution (Error Modes),NaN,NaN,NaN,Observation,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,UPSTREAM,Piper Alpha,1988,"Moura, Raphael:\r\nTiming (Too early): Started...","Moura, Raphael:\r\nToo little force (torque) o...",NaN,NaN,"Moura, Raphael:\r\noverlook cue/signal: not re...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Moura, Raphael:\r\nWrong position of quarters,...",NaN,NaN
4,2,PETROCHEMICALS,Pasadena,1989,"Moura, Raphael:\r\nTiming (Too early): lockout...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,3,UPSTREAM,Ekofisk,2009,"Moura, Raphael:\r\n1) Omission: Duty officer f...","Moura, Raphael:\r\nSpeed: vessel manoeuvred to...",NaN,"Moura, Raphael:\r\nSequence (jump forward): du...","Moura, Raphael:\r\n1) overlook measurement: du...","Moura, Raphael:\r\nFalse recognition: event (m...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Moura, Raphael:\r\nresting time regulations we..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,234,NUCLEAR,Windscale Works,1970,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,235,NUCLEAR,Idaho Chemical Processing Plant,1978,NaN,NaN,NaN,"Moura, Raphael:\r\nWrong Action: operator redu...","Moura, Raphael:\r\nOperator did not notice tha...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,236,NUCLEAR,Siberian Chemical Combine,1978,NaN,NaN,"Moura, Raphael:\r\nOperator B transferred ingo...","Moura, Raphael:\r\nWrong action: Operator A tr...",NaN,"Moura, Raphael:\r\nFalse recognition: Operator...",...,NaN,NaN,NaN,NaN,NaN,NaN,"Moura, Raphael:\r\ntime pressure: operator was...",NaN,NaN,NaN
239,237,NUCLEAR,Novosibirsk Chemical Concentration Plant,1997,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,238,NUCLEAR,"JCO Fuel Fabrication Plant, Japan",1999,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
#organize by year

qualc_year = qualc.sort_values(by='YEAR', ascending=True)

#by industry
qualc_industry = qualc.sort_values(by='INDUSTRY', ascending=True)

#by location
qualc_loc = qualc.sort_values(by='LOCATION', ascending=True)

qualc_year

2,INCIDENT ID,INDUSTRY,LOCATION,YEAR,Wrong Time,Wrong Type,Wrong Object,Wrong Place,Observation Missed,False Observation,...,Temperature,Sound,Humidity,Illumination,Other,Adverse ambient conditions,Excessive demand,Inadequate work place layout,Inadequate team support,Irregular working hours
219,217,NUCLEAR,"Mayak, Russia",1953,NaN,NaN,NaN,"Moura, Raphael:\r\nWrong action/omission: oper...","Moura, Raphael:\r\nOperators did not observed ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,218,NUCLEAR,"Mayak, Russia",1957,NaN,NaN,NaN,"Moura, Raphael:\r\nWrong action: operator inst...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221,219,NUCLEAR,"Mayak, Russia",1958,NaN,NaN,NaN,"Moura, Raphael:\r\nWrong Action: neutron sourc...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,220,NUCLEAR,"Oak Ridge Y-12 Plant, Russia",1958,NaN,NaN,NaN,"Moura, Raphael:\r\nJump forward: operator open...","Moura, Raphael:\r\noperator stationed near the...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,221,NUCLEAR,"Los Alamos Scientific Laboratory, USA",1958,NaN,NaN,NaN,"Moura, Raphael:\r\nSequence, jump forward: une...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,205,AVIATION,Birmingham,2013,"Moura, Raphael:\r\nOmission: Performance data ...",NaN,NaN,"Moura, Raphael:\r\nOmission: \r\n1) first offi...","Moura, Raphael:\r\n1) “sink rate” alert do not...","Moura, Raphael:\r\nFalse recognition: The capt...",...,NaN,NaN,NaN,NaN,NaN,NaN,"Moura, Raphael:\r\nWith limited time and altit...",NaN,"Moura, Raphael:\r\nInadequate communication: \...","Moura, Raphael:\r\n1) acute sleep loss resulti..."
216,214,CONSTRUCTION,"Telecom Tower, Canada",?,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,213,CONSTRUCTION,"Parking, Canada",?,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,Action,NaN,NaN,NaN,Specific Cognitive Functions,NaN,...,Ambient Conditions,NaN,NaN,NaN,NaN,NaN,Working Conditions,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,Execution (Error Modes),NaN,NaN,NaN,Observation,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN